version: '3.4'

services:
  team-report-app:
    container_name: team-report-app-container
    build:
      context: .
    ports:
      - 3000:80
    environment:
      - VITE_TOQUI_JIRA_REPORT_API=http://localhost:5555/api/report

networks:
  default:
    name: global
    external: true