version: '3.4'

services:
  team-report-app:
    container_name: team-report-app-container
    build:
      context: .
    ports:
      - 3000:80
    environment:
      - NODE_ENV=local

networks:
  default:
    name: global
    external: true