export { default as TrSpinner} from "./tr-spinner/tr-spinner";
export { default as TrBox} from "./tr-box/tr-box";
export { default as TrContainer} from "./tr-container/toqui-container";
export { default as TrMainCard} from "./tr-main-card/tr-main-card";
export { default as TrTitle} from "./tr-title/tr-title";
export { default as TrSubTitle} from "./tr-subtitle/tr-subtitle";
export { default as TrThirdTitle} from "./tr-thirdtitle/tr-thirdtitle";
export { default as TrParagraph} from "./tr-paragraph/tr-paragraph";
export { default as TrInputTag} from "./tr-input-tag/tr-input-tag";